apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "provider.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provider.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
